sudo: required
language: python
python:
  - "3.6"

services:
  - docker

install:
  - sudo pip install docker-compose

script:
  - docker-compose build tests-pipeline
  - docker-compose run --rm tests-pipeline
