sudo: required
language: python
python:
  - "3.6"

services:
  - docker

install:
  - sudo pip install docker-compose

script:
  - cd docker
  - docker-compose build
  - docker-compose run --rm tests
